### ISSUE TITLE
gambar admin rusak

### ISSUE THREAD

**Issue by ahmad-reza619** [iColdPlayer/kasir#5]
![Screen Shot 2020-03-10 at 10 09 09](https://user-images.githubusercontent.com/52902060/76275972-3f5fc680-62b7-11ea-971c-ddb17bbf8fab.png)
lihat di kanan atas, gambar admin broken 🤔

**Comment by iColdPlayer** [comment]
You have to set up your own web server e.g. Nginx or Apache to serving media files during production when the debug set to `DEBUG=False`.
here an [example](https://stackoverflow.com/questions/8370658/how-to-serve-django-media-files-via-nginx).

---

betul, karena itu hanya demo dengan `DEBUG = False` menggunakan heroku, sedangkan sewaktu production harus menggunakan web server seperti nginx / apache untuk handling media yang diupload oleh user.

**Comment by ahmad-reza619** [comment]
well it could be nice for the preview if it's not broken

well if it's an expected issue, i will close this
